# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - id: eru-core-debug
    binary: eru-core.dbg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/projecteru2/core/version.REVISION={{.Commit}}
      - -X github.com/projecteru2/core/version.VERSION={{.Env.VERSION}}
      - -X github.com/projecteru2/core/version.BUILTAT={{.Date}}
    hooks:
      post:
        - cp {{.Path}} ./eru-core-{{.Os}}.dbg
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  # the best practice is using prebuilt builder
  # however it's a Pro feature
  - id: eru-core-linux
    binary: eru-core
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/projecteru2/core/version.REVISION={{.Commit}}
      - -X github.com/projecteru2/core/version.VERSION={{.Env.VERSION}}
      - -X github.com/projecteru2/core/version.BUILTAT={{.Date}}
    hooks:
      post:
        - cp ./eru-core-{{.Os}}.dbg {{.Path}}
        - strip {{.Path}}
    goos:
      - linux
    goarch:
      - amd64

  - id: eru-core-darwin
    binary: eru-core
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X github.com/projecteru2/core/version.REVISION={{.Commit}}
      - -X github.com/projecteru2/core/version.VERSION={{.Env.VERSION}}
      - -X github.com/projecteru2/core/version.BUILTAT={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: core
    name_template: >-
      {{- .ProjectName }}_{{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
